# Generated by Django 4.1.4 on 2022-12-27 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0003_geeksmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeeksModel',
        ),
    ]
